language: ruby
rvm:
- 2.3.0
env:
- DB=postgres
before_script:
- rake db:migrate
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/
deploy:
  provider: heroku
  app: rocky-retreat-26336
  api_key:
    secure: O8D67xNLLoHhrN/Rxr/gstid6BFyjkdyux2llsBjSoOK1u0XFwMn2R1Sq9oVlPA2WtbERDicZ6OlakWhut82/nKW5GS002vTjgt4EhHiaGGXWN6UAvGLFBj4Hy8/ildT2xht+f3QRdIbpqRJj6dj9cflHdgQmq0yYuyLBinuPq24IT0pcNHVZOb8uS1mKAskmDf/DdZCb7A1ukgDc9LmYoKO2OJuDvdgdq7GhHTJc4t7BHG7K1q8Dok4+u/kZkeDev8xwh8d/cd7WPu82EzH4cSO0PIkRXIWKd9XY/UUaxAxbVoZxfAWlOfYnhl3F/1wuWPOsblfgWafLYkI5acV5KwAube3qhiwQhjFu0VgV9KoqD3TxvSz48a74QD3tZC1hll3ZHWMpM3WbZ1oOr0NCAGtLbkybMDBwxxJVb2M8MpBna+rsipZ4loYtJptmsYyt98PO4iLfgq1Z8o28rFZ8KY4LXAlHimCP9MqkHR8fR4qCX9mEwURMqSnN0ZvC4JC4gAbQFho1TNNmRxEi1MUKbA9n4V3u+q4Fw6gHVLXVS40f4ACksmbDdvIuBgzTb0O3FX7sNBsAOauqy70a3cjrUd6xaW0plocghV4Xyapz/rSLTRVktpWTlyYuWiZwiabgrqsS4AaZU26G0/48qyUz7DkLJQYCkpzNvLxYwmXtpE=
